/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: silvercrow101 (https://sketchfab.com/silvercrow101)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/space-boi-f6a8c6a6727b4f2cb020c8b50bb2ee60
Title: space boi
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useMotionValue, useSpring } from "motion/react"
import { useFrame, useThree } from "@react-three/fiber"

export function Astronaut(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/space_boi.glb')
  
  // Estado para controlar se está arrastando
  const [isDragging, setIsDragging] = useState(false);
  const dragStartX = useRef(0);
  const lastX = useRef(0);
  const velocity = useRef(0);
  const currentRotation = useRef(0);
  
  // Animação de entrada - subindo de baixo
  const yPosition = useMotionValue(-15);
  const ySpring = useSpring(yPosition, { damping: 20, stiffness: 50 });
  
  // Spring para rotação suave e densa
  const rotationY = useMotionValue(0);
  const rotationYSpring = useSpring(rotationY, { damping: 35, stiffness: 50 });
  
  useEffect(() => {
    ySpring.set(props.position?.[1] || 0);
  }, [ySpring, props.position]);
  
  // Handlers para arrastar
  const handlePointerDown = (e) => {
    e.stopPropagation();
    setIsDragging(true);
    dragStartX.current = e.clientX;
    lastX.current = e.clientX;
    velocity.current = 0;
  };
  
  const handlePointerUp = () => {
    if (isDragging) {
      setIsDragging(false);
      // Mantém a velocidade para continuar o movimento com inércia
    }
  };
  
  const handlePointerMove = (e) => {
    if (isDragging) {
      const deltaX = e.clientX - lastX.current;
      velocity.current = deltaX * 0.0005; // Calcula velocidade baseada no movimento
      currentRotation.current += velocity.current;
      rotationY.set(currentRotation.current);
      lastX.current = e.clientX;
    }
  };
  
  useEffect(() => {
    if (isDragging) {
      window.addEventListener('pointermove', handlePointerMove);
      window.addEventListener('pointerup', handlePointerUp);
      return () => {
        window.removeEventListener('pointermove', handlePointerMove);
        window.removeEventListener('pointerup', handlePointerUp);
      };
    }
  }, [isDragging]);
  
  // Rotação com inércia natural
  useFrame((state, delta) => {
    if (group.current) {
      // Movimento de entrada
      group.current.position.y = ySpring.get();
      
      // Se não está arrastando, aplica inércia e fricção
      if (!isDragging) {
        // Movimento de rotação inicial lento
        if (Math.abs(velocity.current) < 0.001) {
          velocity.current = 0.002; // Velocidade mínima suave
        }
        
        // Aplica a velocidade atual à rotação
        currentRotation.current += velocity.current;
        
        // Aplica fricção muito suave para desacelerar naturalmente
        velocity.current *= 0.995;
        
        // Define a nova rotação
        rotationY.set(currentRotation.current);
      }
      
      // Aplica a rotação com spring (sempre suave)
      group.current.rotation.y = rotationYSpring.get();
      
      // Remove rotações nos outros eixos - mantém modelo estável
      group.current.rotation.x = 0;
      group.current.rotation.z = 0;
    }
  });
  
  return (
    <group 
      ref={group}
      dispose={null}
      scale={props.scale || 0.5}
      position={[props.position?.[0] || 0, 0, props.position?.[2] || 0]}
      onPointerDown={handlePointerDown}
      style={{ cursor: isDragging ? 'grabbing' : 'grab' }}
    >
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.body_Material001_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.body_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group position={[-357.404, 392.646, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={39.706}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere002_Material001_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere002_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[199.634, 566.883, -221.001]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={39.706}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere007_Material001_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere007_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.waves_Material002_0.geometry}
          material={materials['Material.002']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[100, 100, 1.891]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.waves1_Material002_0.geometry}
          material={materials['Material.002']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[100, 100, 1.891]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.waves2_Material002_0.geometry}
          material={materials['Material.002']}
          position={[92.464, 15.529, 2.112]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[100, 100, 1.891]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.particles_Material002_0.geometry}
          material={materials['Material.002']}
          position={[489.69, 793.811, 355.293]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={20.408}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_Material001_0.geometry}
          material={materials['Material.001']}
          position={[375.469, 427.948, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={62.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_Material002_0.geometry}
          material={materials['Material.002']}
          position={[375.469, 427.948, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={60.324}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere004_Material002_0.geometry}
          material={materials['Material.002']}
          position={[375.469, 427.948, 0]}
          rotation={[-0.688, 0, 0]}
          scale={[104.129, 81.609, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere005_Material001_0.geometry}
          material={materials['Material.001']}
          position={[-341.988, 460.196, -117.028]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={62.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere006_Material002_0.geometry}
          material={materials['Material.002']}
          position={[-341.988, 460.196, -117.028]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={60.324}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere009_Material002_0.geometry}
          material={materials['Material.002']}
          position={[507.522, 667.594, -214.475]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={16.881}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere010_Material002_0.geometry}
          material={materials['Material.002']}
          position={[-287.442, 585.792, -311.857]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={16.881}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere011_Material002_0.geometry}
          material={materials['Material.002']}
          position={[-553.462, 331.074, -379.067]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={11.437}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, -101.673, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1120.013, 1120.013, 100]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere003_Material002_0.geometry}
          material={materials['Material.002']}
          position={[-357.404, 392.646, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={41.075}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere008_Material002_0.geometry}
          material={materials['Material.002']}
          position={[199.634, 566.883, -221.001]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={41.075}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/space_boi.glb')